blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('blogs_list/', BlogListView.as_view(), name='blogs_list'),
    path("blog/<int:pk>/", BlogDetailView.as_view(), name="blog_detail"),
    path("create/", BlogCreateView.as_view(), name="blog_create"),
    path("blog/<int:pk>/update/", BlogUpdateView.as_view(), name="blog_update"),
    path("blog/<int:pk>/delete/", BlogDeleteView.as_view(), name="blog_delete"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('', include('blog.urls', namespace='blog')),
    path("users/", include("users.urls", namespace="users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class Blog(models.Model):
    title = models.CharField(max_length=60, verbose_name="Заголовок", help_text="Введите заголовок блога")
    content = models.TextField(verbose_name="Содержимое", help_text="Введите содержимое блога")
    preview = models.ImageField(upload_to="blog_images", verbose_name="Изображение",
                                help_text="Загрузите изображение блога", blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    is_published = models.BooleanField(default=True, verbose_name="Опубликовать",
                                       help_text="Отметьте для публикации")
    views_count = models.PositiveIntegerField(
        default=0, verbose_name="Просмотры", help_text="Количество просмотров")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Блог"
        verbose_name_plural = "Блоги"
        ordering = ["-created_at"]

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from .models import Blog


class BlogListView(ListView):
    model = Blog
    context_object_name = "blogs"

    def get_queryset(self):
        return Blog.objects.filter(is_published=True)


class BlogDetailView(LoginRequiredMixin, DetailView):
    model = Blog
    context_object_name = "blog"

    def get_object(self, queryset=None):
        blog = super().get_object(queryset)
        blog.views_count += 1
        blog.save()
        return blog


class BlogCreateView(LoginRequiredMixin, CreateView):
    model = Blog
    template_name = "blog/blog_form.html"
    fields = ("title", "content", "preview")
    success_url = reverse_lazy("blog:blogs_list")


class BlogUpdateView(LoginRequiredMixin, UpdateView):
    model = Blog
    template_name = "blog/blog_form.html"
    fields = ("title", "content", "preview")
    success_url = reverse_lazy("blog:blogs_list")

    def get_success_url(self):
        return reverse("blog:blog_detail", args=[self.kwargs.get("pk")])


class BlogDeleteView(LoginRequiredMixin, DeleteView):
    model = Blog
    context_object_name = "blog"
    success_url = reverse_lazy("blog:blogs_list")

blog/templates/blog/base.html
<!doctype html>
<html lang="ru">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} Travel Shop : Блоги Путешественников {% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="/static/css/bootstrap.min.css">
</head>

<body>

{% include 'catalog/header_nav.html' %}

{% block content %} Контент страницы {% endblock %}

{% include 'catalog/footer.html' %}

</body>
</html>

blog/templates/blog/blog_confirm_delete.html
<!-- blog_confirm_delete.html -->

{% extends 'blog/base.html' %}

{% block content %}

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header text-center">
                    <h4>Удалить пост</h4>
                </div>
                <div class="card-body text-center">
                    <p class="card-text">Действительно хотите удалить пост: "{{ blog.title }}"?</p>
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}

                        <div class="row row-cols-1 row-cols-md-2 g-1 ">
                            <div class="col">
                                <div class="d-flex justify-content-center align-items-center mb-5">

                                    <button type="submit" class="btn btn-lg btn-block btn-danger">Удалить
                                    </button>
                                </div>
                            </div>
                            <div class="col">
                                <div class="d-flex justify-content-center align-items-center mb-5">
                                    <a href="{% url 'blog:blogs_list' %}">
                                        <button type="button" class="btn btn-lg btn-block btn-outline-primary">Отменить
                                        </button>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/blog_detail.html
<!-- blog_detail.html -->

{% extends 'blog/base.html' %}

{% block content %}

<div class="container">
    <div class="row row-cols-1 row-cols-md-1 g-4">
        <div class="col">
            <div class="card mb-4 box-shadow">
                <div class="card-header text-center">
                    <h4 class="my-0 font-weight-normal">{{ blog.title }}</h4>
                </div>
                <div class="card-body">
                    <div class="d-flex justify-content-center align-items-center mb-5">
                        <img src="/media/{{ blog.preview|default:'/blog_images/ufo_icon.png'}}" alt="{{ blog.title }}">
                    </div>
                    <h4>История:</h4>
                    <p>{{ blog.content }}</p><br>
                    <p align="right"><i>Дата создания: {{ blog.created_at }}</i></p>
                    <div class="row row-cols-1 row-cols-md-1 g-4 ">
                        <div class="col">
                            <div class="d-flex justify-content-center align-items-center mb-5">
                                <a href="{% url 'blog:blogs_list' %}">
                                    <button type="button" class="btn btn-lg btn-block btn-outline-primary">Назад
                                    </button>
                                </a>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
</div>

{% endblock %}

blog/templates/blog/blog_form.html
<!-- blog_form.html -->

{% extends 'blog/base.html' %}

{% block content %}

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header text-center">
                    <h4>Создать пост</h4>
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            {{ form.as_p }}
                        </div>
                        <button type="submit" class="btn btn-primary btn-block">
                            {% if form.instance.pk %}
                            Сохранить
                            {% else %}
                            Создать
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/blog_list.html
<!-- blog_list.html -->

{% extends 'blog/base.html' %}

{% block content %}

<div class="container mt-3">
    <div class="text-center">
        <h1>Блоги Путешественников</h1>
        <br>
    </div>
    <div class="row mt-3">

        {% for blog in blogs %}
        <div class="col-sm-4 mb-4">
            <div class="card text-center" style="height: 100%;">
                <img src="/media/{{ blog.preview|default:'/blog_images/ufo_icon.png'}}" alt="{{ blog.title }}"
                     class="img-fluid">
                <div class="card-body d-flex flex-column">
                    <h5 class="card-header">{{ blog.title }}</h5>
                    <p class="card-text">{{ blog.content|truncatechars:200 }}</p>
                    <p class="card-text">Количество просмотров: {{ blog.views_count }}</p>

                    <div class="mt-auto d-flex justify-content-between">
                        <div>
                            <a class="btn btn-primary me-2" href="{% url 'blog:blog_detail' blog.pk %}" role="button">Посмотреть</a>
                            {% if user.is_authenticated %}
                            <a class="btn btn-primary" href="{% url 'blog:blog_update' blog.pk %}" role="button">Редактировать</a>
                            {% endif %}
                        </div>
                        {% if user.is_authenticated %}
                        <a class="btn btn-danger" href="{% url 'blog:blog_delete' blog.pk %}" role="button">Удалить</a>
                        {% endif %}
                    </div>

                </div>
            </div>
        </div>
        {% empty %}
        <!-- Если нет блогов -->
        <div class="col-12 text-center">
            <p>Нет опубликованных блогов.</p>
        </div>
        {% endfor %}

    </div>

    {% if user.is_authenticated %}
    <div class="text-center">
        <a class="btn btn-primary btn-lg shadow" href="{% url 'blog:blog_create' %}" role="button">Добавить пост</a>
        <br>
    </div>
    {% endif %}

</div>

{% endblock %}