blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('blogs_list/', BlogListView.as_view(), name='blogs_list'),
    path("blog/<int:pk>/", BlogDetailView.as_view(), name="blog_detail"),
    path("create/", BlogCreateView.as_view(), name="blog_create"),
    path("blog/<int:pk>/update/", BlogUpdateView.as_view(), name="blog_update"),
    path("blog/<int:pk>/delete/", BlogDeleteView.as_view(), name="blog_delete"),
]

catalog/urls.py
from django.urls import path
from catalog.apps import CatalogConfig
from .views import ProductListView, ProductDetailView, HomeTemplateView, ContactsTemplateView, ProductCreateView, \
    ProductUpdateView, ProductDeleteView, CategoryListView

app_name = CatalogConfig.name

urlpatterns = [
    path('', HomeTemplateView.as_view(), name='home'),
    path('contacts/', ContactsTemplateView.as_view(), name='contacts'),
    path('product_list/', ProductListView.as_view(), name='product_list'),
    path('product_detail/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
    path("create/", ProductCreateView.as_view(), name="product_create"),
    path("product/<int:pk>/update/", ProductUpdateView.as_view(), name="product_update"),
    path("product/<int:pk>/delete/", ProductDeleteView.as_view(), name="product_delete"),
    path('category_list/<int:id>/', CategoryListView.as_view(), name='category_list'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('', include('blog.urls', namespace='blog')),
    path("users/", include("users.urls", namespace="users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import UserCreateView, email_verification

app_name = UsersConfig.name

urlpatterns = [
    path("login/", LoginView.as_view(template_name="users/login.html"), name="login"),
    path('logout/', LogoutView.as_view(next_page=''), name='logout'),
    path("register/", UserCreateView.as_view(), name="register"),
    path("email-confirm/<str:token>/", email_verification, name="email-confirm"),
]

catalog/models.py
from django.db import models

from users.models import User


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='Имя_категории')
    description = models.TextField(verbose_name='Описание_категории')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ['name']


class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name='Имя_продукта')
    description = models.TextField(verbose_name='Описание_продукта')
    image = models.ImageField(upload_to='product_images/', verbose_name='Изображение_продукта', blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='product')
    price = models.IntegerField(verbose_name='Цена_продукта')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    STATUS_CHOICES = [
        ('unpublished', 'Не опубликован'),
        ('published', 'Опубликован'),
    ]

    status = models.CharField(
        max_length=15,
        choices=STATUS_CHOICES,
        default='unpublished',
        verbose_name='Статус публикации',
    )

    owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f'{self.name} {self.category}'

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        ordering = ['name']
        permissions = [
            ("can_unpublish_product", "Can unpublish product"),
        ]

catalog/forms.py
from django.forms import ModelForm, forms, BooleanField
from .models import Product

FORBIDDEN_WORDS = [
    "казино",
    "криптовалюта",
    "крипта",
    "биржа",
    "дешево",
    "бесплатно",
    "обман",
    "полиция",
    "радар",
]


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs["class"] = "form-check-input"
            else:
                field.widget.attrs["class"] = "form-control"


class ProductForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Product
        exclude = ('status', "owner")

    def clean(self):
        cleaned_data = super().clean()
        name = cleaned_data.get("name")
        description = cleaned_data.get("description")

        if name:
            self.validate_forbidden_words(name, 'name')
        if description:
            self.validate_forbidden_words(description, 'description')
        return cleaned_data

    def validate_forbidden_words(self, value, field):
        for word in FORBIDDEN_WORDS:
            if word.lower() in value.lower():
                self.add_error(field, f"Слово '{word}' запрещено.")

    def clean_price(self):
        price = self.cleaned_data.get("price")

        if price is not None and price < 0:
            raise forms.ValidationError("Цена не может быть отрицательной.")
        return price


class ProductModeratorForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Product
        fields = ("id", "status")

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.http import HttpResponseForbidden
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from django.views.generic import ListView, DetailView, TemplateView, CreateView, UpdateView, DeleteView

from .forms import ProductForm, ProductModeratorForm
from .models import Product, Category
from .services import get_products_from_cache, get_categories_from_cache, get_products_from_category


class HomeTemplateView(TemplateView):
    template_name = "catalog/index.html"


class ContactsTemplateView(TemplateView):
    template_name = "catalog/contacts.html"


class CategoryListView(ListView):
    model = Category
    context_object_name = 'categories'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        category_id = self.kwargs.get("id")
        context['current_category_id'] = category_id
        context['products'] = get_products_from_category(category_id)
        return context


class ProductListView(ListView):
    model = Product
    context_object_name = 'products'

    def get_queryset(self):
        queryset = get_products_from_cache()
        return queryset.order_by('id')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # categories = get_categories_from_cache()
        context['categories'] = get_categories_from_cache()
        return context


@method_decorator(cache_page(60 * 15), name='dispatch')
class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product
    context_object_name = 'product'


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    template_name = "catalog/product_form.html"
    form_class = ProductForm
    success_url = reverse_lazy("catalog:product_list")

    def form_valid(self, form):
        user = self.request.user

        if user.has_perm('catalog.can_unpublish_product') and not user.has_perm('is_superuser'):
            return HttpResponseForbidden("У модераторов нет прав для создания продукта.")

        form.instance.owner = user
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    template_name = "catalog/product_form.html"
    form_class = ProductForm
    success_url = reverse_lazy("catalog:product_list")

    def get_success_url(self):
        return reverse("catalog:product_detail", args=[self.kwargs.get("pk")])

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner:
            return ProductForm
        if user.has_perm("catalog.can_unpublish_product"):
            return ProductModeratorForm
        raise PermissionDenied


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    context_object_name = "product"
    success_url = reverse_lazy("catalog:product_list")

    def form_valid(self, form):
        user = self.request.user
        if user == self.object.owner or user.has_perm('catalog.can_unpublish_product'):
            return super().form_valid(form)
        return HttpResponseForbidden("У вас нет прав для удаления продукта.")

catalog/templates/catalog/base.html
<!doctype html>
<html lang="ru">

{% include 'catalog/header.html' %}

<body>

{% include 'catalog/header_nav.html' %}

{% block content %} Контент страницы {% endblock %}

{% include 'catalog/footer.html' %}

</body>
</html>

catalog/templates/catalog/category_list.html
<!-- category_list.html -->

{% extends 'catalog/base.html' %}

{% block title %} Travel Shop : Каталог {% endblock %}

{% block content %}

{% include 'catalog/category_nav.html' %}

<!--Список продуктов по категории -->

<div class="container">
    <div class="row row-cols-1 row-cols-md-2 g-4">

        {% for product in products %}

        {% if product.status == "published" or perms.catalog.can_unpublish_product or user == product.owner %}
        <div class="col">
            <div class="card mb-4 box-shadow">
                <div class="card-header text-center">
                    <h4 class="my-0 font-weight-normal">{{ product.name }}</h4>
                </div>
                <div class="card-body">
                    <div class="d-flex justify-content-center align-items-center mb-3">
                        <img src="/media/{{ product.image|default:'/product_images/no_image.png'}}" class="img-fluid"
                             style="height: 250px;"
                             alt="{{ product.name }}">
                    </div>
                    <p>{{ product.description|truncatechars:100 }}</p>

                    <div class="row row-cols-1 row-cols-md-2 g-4">
                        <div class="col">
                            <a href="{% url 'catalog:product_detail' product.id %}">
                                <button type="button" class="btn btn-lg btn-block btn-outline-primary">
                                    {{ product.price }} руб.
                                </button>
                            </a>
                        </div>
                        {% if user.is_authenticated %}

                        {% if perms.catalog.can_unpublish_product or user == product.owner %}

                        <div class="col">
                            <div class="mt-auto d-flex justify-content-end">
                                <div>
                                    <a class="btn btn-primary" href="{% url 'catalog:product_update' product.pk %}"
                                       role="button">
                                        {% if perms.catalog.can_unpublish_product and not perms.is_superuser %}
                                        Публикация
                                        {% else %}
                                        Редактировать
                                        {% endif %}
                                    </a>
                                </div>
                                <a class="btn btn-danger" href="{% url 'catalog:product_delete' product.pk %}"
                                   role="button">Удалить</a>
                            </div>
                        </div>
                        {% endif %}
                        {% endif %}
                    </div>
                </div>

                {% if perms.catalog.can_unpublish_product or user == product.owner %}

                {% if product.status == "unpublished" %}
                <div class="card-footer text-white bg-danger text-center">
                    {{ product.status }}
                </div>
                {% else %}
                <div class="card-footer text-white bg-success text-center">
                    {{ product.status }}
                </div>
                {% endif %}
                {% endif %}

            </div>
        </div>

        {% endif %}

        {% endfor %}
    </div>
    {% if user.is_authenticated and not perms.catalog.can_unpublish_product or perms.is_superuser %}
    <div class="text-center">
        <a class="btn btn-primary btn-lg shadow" href="{% url 'catalog:product_create' %}" role="button">Добавить
            продукт</a>
        <br>
    </div>
    {% endif %}
</div>

<!--Список продуктов по категории - конец-->

{% endblock %}

catalog/templates/catalog/category_nav.html
<!-- category_nav.html -->

<!--Категории панель навигации-->

<div class="container">
    <div class="row row-cols-1 row-cols-md-2 g-4 align-items-center justify-content-center">
        <nav class="navbar navbar-light  navbar-expand-lg justify-content-center">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <p class="nav-link">Категории: </p>
                </li>
                {% for category in categories %}
                <li class="nav-item">
                    <a class="nav-link {% if current_category_id == category.id %} disabled {% endif %}"
                       href="{% url 'catalog:category_list' category.id %}">{{ category.name }}</a>
                </li>
                {% empty %}
                <p>Нет категорий</p>
                {% endfor %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'catalog:product_list' %}">Все категории</a>
                </li>
            </ul>
        </nav>
    </div>
</div>

<!--Категории панель навигации - конец-->

catalog/templates/catalog/contacts.html
<!-- contacts.html -->
{% extends 'catalog/base.html' %}

{% block content %}

<!-- Контакты -->
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>Россия</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>7777777</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Москва, Сивашская улица, 4/2</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"
                                   required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone"
                                   placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message"
                                      placeholder="Напишите Ваш запрос" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Контакты - конец-->

{% endblock %}

catalog/templates/catalog/footer.html
<!--Нижняя панель-->
<div class="container">
    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                Travel Shop
                <small class="d-block mb-3 text-muted">&copy; 2025</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="{% url 'blog:blogs_list' %}">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>
<!--Нижняя панель - конец-->

<script src="/static/js/bootstrap.bundle.min.js"></script>

catalog/templates/catalog/header.html
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} Travel Shop {% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="/static/css/bootstrap.min.css">
</head>

catalog/templates/catalog/header_nav.html
<!--Верхняя панель навигации-->
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Travel Shop</h5>
    <nav class="navbar navbar-light bg-light navbar-expand-lg ms-5">
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:product_list' %}">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'blog:blogs_list' %}">Блоги Путешественников</a>
        <ul class="navbar-nav">
            <li class="nav-item">
                <pre class="nav-item">         </pre>
            </li>

            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href=#">( Профиль </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href=#"> | </a>
            </li>
            <li class="nav-item">
                <form method="post" action="{% url 'users:logout' %}" style="display: inline;">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-link nav-link"> Выйти : {{ user.email }} )
                    </button>
                </form>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:login' %}">( Вход </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href=#"> | </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:register' %}"> Регистрация )</a>
            </li>
            {% endif %}

        </ul>
    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Travel Shop</h1>
    <p class="lead">Travel Shop - это отличный способ найти приключение по своему вкусу</p>
</div>
<!--Верхняя панель навигации - конец-->

catalog/templates/catalog/index.html
<!-- index.html -->
{% extends 'catalog/base.html' %}

{% block content %}

<!-- Index -->

<div class="container">
    <div class="row row-cols-1 row-cols-md-1 g-4">
        <div class="col">
            <div class="card mb-4 box-shadow">
                <div class="card-header text-center">
                    <h4 class="my-0 font-weight-normal">Портал поиска вашего приключения</h4>
                </div>
                <div class="card-body">
                    <div class="d-flex justify-content-center align-items-center mb-5">
                        <img src="/media/product_images/travel_intro.jpeg" class="img-fluid"
                             alt="Image">
                    </div>

                    <div class="row row-cols-1 row-cols-md-1 g-4 ">
                        <div class="col">
                            <div class="d-flex justify-content-center align-items-center mb-5">
                                <a href="{% url 'catalog:product_list' %}">
                                    <button type="button" class="btn btn-lg btn-block btn-outline-primary">Начать поиск
                                    </button>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Index - конец-->

{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
<!-- product_confirm_delete.html -->

{% extends 'catalog/base.html' %}

{% block content %}

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header text-center">
                    <h4>Удалить продукт</h4>
                </div>
                <div class="card-body text-center">
                    <p class="card-text">Действительно хотите удалить продукт: "{{ product.name }}"?</p>
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="row row-cols-1 row-cols-md-2 g-1 ">
                            <div class="col">
                                <div class="d-flex justify-content-center align-items-center mb-5">
                                    <button type="submit" class="btn btn-lg btn-block btn-danger">Удалить
                                    </button>
                                </div>
                            </div>
                            <div class="col">
                                <div class="d-flex justify-content-center align-items-center mb-5">
                                    <a href="{% url 'catalog:product_list' %}">
                                        <button type="button" class="btn btn-lg btn-block btn-outline-primary">Отменить
                                        </button>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

catalog/templates/catalog/product_detail.html
<!-- product_detail.html -->

{% extends 'catalog/base.html' %}

{% block title %} Travel Shop : Каталог {% endblock %}

{% block content %}

<!--Продукт-->
<div class="container">
    <div class="row row-cols-1 row-cols-md-1 g-4">
        <div class="col">
            <div class="card mb-4 box-shadow">
                <div class="card-header text-center">
                    <h4 class="my-0 font-weight-normal">{{ product.name }}</h4>
                </div>
                <div class="card-body">
                    <div class="d-flex justify-content-center align-items-center mb-5">
                        <img src="/media/{{ product.image|default:'/product_images/no_image.png'}}" class="img-fluid"
                             alt="{{ product.name }}">
                    </div>
                    <h3>Описание:</h3>
                    <p>{{ product.description }}</p><br>
                    <h3>Категория тура:</h3>
                    <p>{{ product.category }}</p><br>
                    <h3>Цена:</h3>
                    <p><b>{{ product.price }} руб.</b></p><br>
                    <div class="row row-cols-1 row-cols-md-2 g-4 ">
                        <div class="col">
                            <div class="d-flex justify-content-center align-items-center mb-5">
                                <a href="{% url 'catalog:contacts' %}">
                                    <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить
                                    </button>
                                </a>
                            </div>
                        </div>
                        <div class="col">
                            <div class="d-flex justify-content-center align-items-center mb-5">
                                <a href="{% url 'catalog:product_list' %}">
                                    <button type="button" class="btn btn-lg btn-block btn-outline-primary">Каталог
                                    </button>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Продукт - конец-->

{% endblock %}

catalog/templates/catalog/product_form.html
<!-- catalog_form.html -->

{% extends 'catalog/base.html' %}

{% block content %}

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header text-center">
                    {% if form.instance.pk %}
                    <h4>Редактировать продукт</h4>
                    {% else %}
                    <h4>Создать продукт</h4>
                    {% endif %}
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            {{ form.as_p }}
                        </div>
                        <button type="submit" class="btn btn-primary btn-block">
                            {% if form.instance.pk %}
                            Сохранить
                            {% else %}
                            Создать
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

catalog/templates/catalog/product_list.html
<!-- product.html -->

{% extends 'catalog/base.html' %}

{% block title %} Travel Shop : Каталог {% endblock %}

{% block content %}

<!--Список продуктов-->
<div class="container">
    <div class="row row-cols-1 row-cols-md-2 g-4">
        {% for product in products %}

        {% if product.status == "published" or perms.catalog.can_unpublish_product or user == product.owner %}
        <div class="col">
            <div class="card mb-4 box-shadow">
                <div class="card-header text-center">
                    <h4 class="my-0 font-weight-normal">{{ product.name }}</h4>
                </div>
                <div class="card-body">
                    <div class="d-flex justify-content-center align-items-center mb-3">
                        <img src="/media/{{ product.image|default:'/product_images/no_image.png'}}" class="img-fluid"
                             style="height: 250px;"
                             alt="{{ product.name }}">
                    </div>
                    <p>{{ product.description|truncatechars:100 }}</p>

                    <div class="row row-cols-1 row-cols-md-2 g-4">
                        <div class="col">
                            <a href="{% url 'catalog:product_detail' product.id %}">
                                <button type="button" class="btn btn-lg btn-block btn-outline-primary">
                                    {{ product.price }} руб.
                                </button>
                            </a>
                        </div>
                        {% if user.is_authenticated %}

                        {% if perms.catalog.can_unpublish_product or user == product.owner %}

                        <div class="col">
                            <div class="mt-auto d-flex justify-content-end">
                                <div>
                                    <a class="btn btn-primary" href="{% url 'catalog:product_update' product.pk %}"
                                       role="button">
                                        {% if perms.catalog.can_unpublish_product and not perms.is_superuser %}
                                        Публикация
                                        {% else %}
                                        Редактировать
                                        {% endif %}
                                    </a>
                                </div>
                                <a class="btn btn-danger" href="{% url 'catalog:product_delete' product.pk %}"
                                   role="button">Удалить</a>
                            </div>
                        </div>
                        {% endif %}
                        {% endif %}
                    </div>
                </div>

                {% if perms.catalog.can_unpublish_product or user == product.owner %}

                {% if product.status == "unpublished" %}
                <div class="card-footer text-white bg-danger text-center">
                    {{ product.status }}
                </div>
                {% else %}
                <div class="card-footer text-white bg-success text-center">
                    {{ product.status }}
                </div>
                {% endif %}
                {% endif %}

            </div>
        </div>

        {% endif %}

        {% endfor %}
    </div>
    {% if user.is_authenticated and not perms.catalog.can_unpublish_product or perms.is_superuser %}
    <div class="text-center">
        <a class="btn btn-primary btn-lg shadow" href="{% url 'catalog:product_create' %}" role="button">Добавить
            продукт</a>
        <br>
    </div>
    {% endif %}
</div>
<!--Список продуктов - конец-->

{% endblock %}